version: 2

sources:
  - name: raw
    database: lakehouse
    schema: raw
    tables:
      - name: tb_customers
      - name: tb_order_items
      - name: tb_order_payments
      - name: tb_orders
      - name: tb_products
