version: 2

sources:
  - name: slv_data
    database: lakehouse
    schema: slv_data
    tables:
      - name: slv_tb_customers
      - name: slv_tb_order_items
      - name: slv_tb_order_payments
      - name: slv_tb_orders
      - name: slv_tb_products
      - name: slv_tb_order_reviews
      - name: slv_tb_sellers